"""
    @Author: Thorsten liepert <thorsten@liepert.dev>
    @Date: 06.09.2024
    @CLicense: MIT
    @Description: A Discord bot that will handle log files generated by a SCUM server
                  and will send various events to discord.
"""
import http.server
from urllib.parse import urlparse
from urllib.parse import parse_qs

from modules.configmanager import ConfigManager

import templates
import templates.config
import templates.world

class MyHttpRequestHandler(http.server.BaseHTTPRequestHandler):
    """ class """
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        self.send_header("Content-type", "text/html")

        # Whenever using 'send_header', you also have to call 'end_headers'
        self.end_headers()

        cfg = ConfigManager()

        # Extract query param
        name = 'World'
        query_components = parse_qs(urlparse(self.path).query)
        if 'name' in query_components:
            name = query_components["name"][0]

        if urlparse(self.path).path == "/config":
            html = templates.config.web_config_print("http://" + self.address_string() + ":8000")
        else:
            html = templates.world.hello_world(name, cfg)

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

        return

# # Create an object of the above class
# handler_object = MyHttpRequestHandler

# PORT = 8000
# my_server = socketserver.TCPServer(("", PORT), handler_object)

# # Star the server
# my_server.serve_forever()
